# This documentation is for the Southwest API 
swagger: '2.0'
info:
  title: Southwest Api
  description: Grab Southwest flight info without hassle
  version: "0.0.1"
# the domain of the service
host: bqkfahgo2a.execute-api.us-east-1.amazonaws.com
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /prod
produces:
  - application/json
security:
- api_key: []
securityDefinitions:
  api_key:
    type: apiKey
    name: x-api-key
    in: header
paths:
  /flight:
    post:
      summary: Flight Information
      operationId: searchFlight
      description: |
        The flight endpoint allows you to provide information about a flight you are wanting to take and get back a list of available flights
      produces:
        - application/json
      parameters:
        - name: flightRequest
          in: body
          description: Details of flight search
          required: true
          schema:
            $ref: '#/definitions/Flight'
      tags:
        - Flights
      security:
        - api_key: []
      responses:
        200:
          description: An array of flight results
          schema:
            type: array
            items:
              $ref: '#/definitions/FlightResp'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Flight:
    required:
      - origin
      - destination
      - date
    properties:
      origin:
        type: string
        description: Departing airport code
      destination:
        type: string
        description: Arrival airport code.
      date:
        type: string
        description: Date of travel. In the form MM/DD/YYYY.
  FlightResp:
    properties:
      price:
        type: string
        description: Wanna-get-away fare for the flight
      departureTime:
        type: string
        description: Departure time of the flight.
      arrivalTime:
        type: string
        description: Arrival time of the flight.
      flightNum:
        type: string
        description: Flight number(s) for the flight.
      layover:
        type: string
        description: If there is a layover in the flight this will be the layover airport code. If there is no layover this will be an empty string.
  Error:
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
